# Generated by Django 5.2.4 on 2025-07-19 13:14

import django.db.models.deletion
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_price_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title_en",
            field=models.CharField(
                max_length=255,
                validators=[products.validators.validate_english],
                verbose_name="English Title",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_fa",
            field=models.CharField(
                max_length=255,
                validators=[products.validators.validate_persian],
                verbose_name="Persian Title",
            ),
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=255, unique=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "ordering": ["-created_date"],
                "unique_together": {("product", "slug")},
            },
        ),
    ]
