# Generated by Django 5.2.4 on 2025-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_title_en_alter_product_title_fa_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("slug",)},
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(null=True, to="products.productcategory"),
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="product",
        ),
    ]
