# Generated by Django 5.2.4 on 2025-08-01 12:38

import django.db.models.deletion
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=10,
                validators=[products.validators.validate_positive_price],
            ),
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=255, unique=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product color",
                "verbose_name_plural": "Product colors",
                "ordering": ["-created_date"],
                "unique_together": {("slug",)},
            },
        ),
        migrations.CreateModel(
            name="ProductGuarantee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=255, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Guarantee",
                "verbose_name_plural": "Product Guarantees",
                "ordering": ["-created_date"],
                "unique_together": {("slug",)},
            },
        ),
        migrations.CreateModel(
            name="ProductSpecifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                ("value", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Specification",
                "verbose_name_plural": "Product Specifications",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[products.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=255, unique=True
                    ),
                ),
                ("video_url", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product VIdeo",
                "verbose_name_plural": "Product Videos",
                "ordering": ["-created_date"],
                "unique_together": {("slug",)},
            },
        ),
    ]
