# Generated by Django 5.2.4 on 2025-08-02 15:22

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_price_productcolor_productguarantee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productvideos",
            name="cover",
            field=models.ImageField(
                null=True,
                upload_to=products.models.video_image_slug_upload_path,
                verbose_name="Product Image",
            ),
        ),
        migrations.AddField(
            model_name="productvideos",
            name="product",
            field=models.ManyToManyField(null=True, to="products.product"),
        ),
        migrations.AddField(
            model_name="productvideos",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
