# Generated by Django 5.2.4 on 2025-08-02 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productvideos_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(null=True, to="products.productcolor"),
        ),
        migrations.AddField(
            model_name="product",
            name="guarantee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.productguarantee",
            ),
        ),
    ]
