# Generated by Django 5.2.4 on 2025-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_color_product_guarantee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="products.productcategory"),
        ),
    ]
