# Generated by Django 5.2.4 on 2025-07-18 06:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_characteristic_termsconditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, "Title must be at least 10 characters."
                            )
                        ],
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                20, "Answer must be at least 20 characters."
                            )
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["-is_active", "-updated_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "title"],
                        name="website_faq_is_acti_a3dbb4_idx",
                    )
                ],
            },
        ),
    ]
