# Generated by Django 5.2.4 on 2025-07-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_faq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutus",
            name="image",
        ),
    ]
