# Generated by Django 5.2.4 on 2025-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_aboutus_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteristic",
            name="logo",
            field=models.ImageField(null=True, upload_to="website/logo/"),
        ),
    ]
