# Generated by Django 5.2.4 on 2025-07-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
    ]
