# Generated by Django 5.2.4 on 2025-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("admin", "Admin"),
                    ("superuser", "Superuser"),
                ],
                default="customer",
                max_length=10,
                verbose_name="Address Type",
            ),
        ),
    ]
