# Generated by Django 5.2.4 on 2025-07-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("admin", "Admin"),
                    ("superuser", "Superuser"),
                ],
                default="customer",
                max_length=10,
                verbose_name="User Type",
            ),
        ),
    ]
