# Generated by Django 5.2.4 on 2025-07-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Customer"), (2, "Admin"), (3, "Super User")],
                default=1,
                verbose_name="User Type",
            ),
        ),
    ]
