# Generated by Django 5.2.4 on 2025-08-28 06:02

import blog.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[blog.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[blog.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["title_en"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[blog.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[blog.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["title_en"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255,
                        validators=[blog.validators.validate_english],
                        verbose_name="English Title",
                    ),
                ),
                (
                    "title_fa",
                    models.CharField(
                        max_length=255,
                        validators=[blog.validators.validate_persian],
                        verbose_name="Persian Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=256, unique_for_date="created_date"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary of the post",
                        max_length=500,
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_images/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("categories", models.ManyToManyField(to="blog.category")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "ordering": ["-created_date"],
                "get_latest_by": "created_date",
                "indexes": [
                    models.Index(
                        fields=["-created_date", "status"],
                        name="blog_post_created_827271_idx",
                    ),
                    models.Index(fields=["slug"], name="blog_post_slug_cdb902_idx"),
                ],
            },
        ),
    ]
