# Generated by Django 5.2.4 on 2025-08-29 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 8, 29, 12, 15, 31, 787359, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 8, 29, 12, 16, 19, 859651, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
