# Generated by Django 5.2.4 on 2025-08-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_created_date_category_updated_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
    ]
